# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install system requirements
      run: sudo apt-get install portaudio19-dev python3-all-dev
    - uses: actions/checkout@v4
    - uses: eifinger/setup-rye@v4
      id: setup-rye
    - run: rye sync --no-lock
    - name: Test with pytest
      run: |
        rye run py.test
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install system requirements
      run: sudo apt-get install portaudio19-dev python3-all-dev
    - uses: actions/checkout@v4
    - uses: eifinger/setup-rye@v4
      id: setup-rye
    - run: rye sync --no-lock
    - name: Run Black
      run: |
        rye run black .
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git commit -am "chore: Apply Black formatting" || echo "No changes to commit"
        git push
