# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install system requirements
      run: sudo apt-get install portaudio19-dev python-all-dev
    - uses: actions/checkout@v4
    - uses: eifinger/setup-rye@v4
      id: setup-rye
    - run: rye sync --no-lock
    - name: Test with pytest
      run: |
        rye run py.test
